default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: music_share_development

test:
  <<: *default
  database: music_share_test

production:
  <<: *default
  database: music_share_production
  username: music_share
  password: <%= ENV['MUSIC_SHARE_DATABASE_PASSWORD'] %>
